name = "check-videos"
compatibility_date = "2025-01-04"
main = "check-videos.ts"

[[d1_databases]]
binding = "RELAY_DATABASE"
database_name = "nostr-relay"
database_id = "8beb11fa-ff53-462e-82a4-64a8a7db68a2"
